- CHANGELOG.md
- lib/events/new-editorial-comment.php
- package.json
Allows posts to be saved using the REST API.
See #41.
> Fix auth_callback for assignees field

- lib/events/new-comment.php
- lib/recipients/post-author.php
- plugin.php
This adds an event for handling the publishing of an approved comment. It also adds a recipient handler for the author of the corresponding post.
Notes:
* Only applies to the default comment type
* Only applies to approved comments
* Doesn't notify the post author if they are the author of the comment
> Register an event for handling new comments

- lib/events/new-editorial-comment.php
This brings the feature inline with core, which doesn't show filter links for statuses with zero results.
> Don't show an "Assigned to me" link on the post listing screen when nothing is assigned to me

- lib/events/new-editorial-comment.php
The value for the post status isn't dynamic, so the implode isn't necessary.
> Remove unnecessary complexity from the assigned posts query

- lib/recipients/post-assignee.php
- lib/recipients/post-author.php
AFAICT these are duplicates and unnecessary. The actual includes happen here: https://github.com/humanmade/Workflows/blob/42322a3a994c5534a1aaf47556fa540301244361/plugin.php#L28-L29
> Remove unnecessary duplicate includes

- inc/class-workflow.php
My PHP error log is full of the following warnings:
strlen() expects parameter 1 to be string, object given
This is caused by `$recipient` being passed to `is_email()` without first checking that it's a string. It gets passed through to `strlen()` which triggers this warning whenever the recipient is, for example, a `WP_User` object (which it is most of the time).
This change fixes that.
> Ensure recipient is a string before passing it to `is_email()`

- inc/namespace.php
If a stored workflow references a non-existent event type (for example, a workflow was stored for an event type that no longer exists), it causes a fatal error on every page load:
Uncaught Error: Call to a member function get_ui() on null in workflows/inc/namespace.php:195
This change avoids that fatal error.
> Add some defence for non-existent event types

- CHANGELOG.md
- admin/admin.php
- admin/package-lock.json
- admin/src/Comments/index.js
- lib/events/new-editorial-comment.php
- package.json
- plugin.php
The endpoint to fetch assignee metadata was hardcoded to `wp/v2/posts`, it's not possible to accurately get the posts controller endpoint for post types in PHP so this was the safest way to ensure support, gutenberg or no.
> Fix assignees api calls with dedicated endpoint

- CHANGELOG.md
- lib/events/new-comment.php
- lib/events/new-editorial-comment.php
- lib/events/transition-post-status.php
- package.json
- plugin.php
Issue: https://github.com/humanmade/Workflows/issues/84
@roborourke I replaced all `get_the_title()` instances in the `events` folder only to use the post raw title (not put through filters).
Not tested :yolo:, if you could run some tests would be great 👍
> 84 Replace get_the_title() with raw post_title value in the Events folder

- inc/class-event.php
- inc/class-workflow.php
- lib/destinations/dashboard.php
Here is some POC code to add data to the notification itself (instead of or in addition to action data...)
Mostly just getting my head around the internals of this plugin so needs a bit more work - but wanted to share.
> Add data to notification

- CHANGELOG.md
- inc/class-event.php
- package.json
- plugin.php
get_recipient_handler() can also take a user ID directly, in which case there's no handler set. This defaults the value (to avoid warnings), and removes the typehint to avoid crashing PHP if a non-callable function is returned.
> Remove typehinting on get_recipient_handler

- CHANGELOG.md
- inc/namespace.php
- package.json
- plugin.php
The incorrect (non plural) primitive capabilities were being checked in the map_meta_cap filter so site admins never actually had access.
> Fix site admin permissions

- lib/events/transition-post-status.php
Previously these events fired on every update to the content, this properly checks the status transition.
> Ensure publish post/page events only fire once

- CHANGELOG.md
- admin/src/Notifications/index.js
- admin/src/withFetch.js
- package.json
- plugin.php
Changes the poll timeout to 60s rather than 10s! Removes expiry from the cache key in `withFetch` to prevent localStorage item explosion.
> Fix withFetch caching and reduce notification polling

- CHANGELOG.md
- inc/class-rest-workflow-comments-controller.php
- package.json
- plugin.php
Makes two changes to the REST controller for Workflow comments to better align permissions and capabilities with the expected model:
- Prevents users without the capability of editing a post from reading editorial comments on the post
- Limits the /workflows/v1/comments endpoint so that the "post" parameter is required, because querying for comments across all posts is a slow database query.
> Add permission checks to editorial comments endpoints

- CHANGELOG.md
- inc/class-rest-workflow-comments-controller.php
- package.json
- plugin.php
Fixes a logic bug from #148 that bypassed the endpoint permissions check if no post IDs were sent with the request.
> Fix permissions for REST comments collection endpoint

- CHANGELOG.md
- package.json
- plugin.php
Loading stored workflows makes it much easier to register events for custom post types, use REST API for field data, etc.
See  #158.
> Load stored workflows on init hook.

- lib/events/transition-post-status.php
The built publish events cause 2 emails to be sent as both the `publish_page` and `publish_post` action hooks fire when publishing any post.
> Ensure post type is checked before publish event

- CHANGELOG.md
- inc/namespace.php
- package.json
- plugin.php
> Fix permissions hack to allow manage_workflows to be the sole permission needed

- CHANGELOG.md
- inc/class-rest-workflow-comments-controller.php
- plugin.php
Related issue - #189 
When submitting a new editorial comment, there is a fatal error being thrown.
> PHP Fatal error:  Uncaught TypeError: array_reduce(): Argument #1 ($array) must be of type array, int given in /usr/src/app/vendor/humanmade/workflows/inc/class-rest-workflow-comments-controller.php:76
The related function `get_items_permissions_check` was only handling the request for multiple post ID's as an array and triggering a fatal error when receiving a single post ID.
When handling the `$post_ids` during the permission check, if `$post_ids` is **not** an array then do an early return with a permission check.
> Fatal Error when submitting editorial comment.

- CHANGELOG.md
- inc/class-rest-workflow-comments-controller.php
- package.json
- plugin.php
Fixes: https://github.com/humanmade/Workflows/issues/189
> Fix issue 189. Fatal Error when submitting editorial comment

- CHANGELOG.md
- lib/events/new-editorial-comment.php
- package.json
- plugin.php
Related Issue : https://github.com/humanmade/Workflows/issues/194
Currently the comment count is displayed as a combined total of comments and editorial comments. This PR excludes "workflow" comments from the post comment count, giving a true number of comments per post.
> Exclude editorial comments in post comment count.

- CHANGELOG.md
- lib/events/new-editorial-comment.php
- package.json
- plugin.php
**Note**: I have tested that this fixes the bug described below, but I have _not_ tested that it still correctly handles workflow comments. Whatever testing was done to validate #195 should be repeated for this PR, I did not see any PHP unit tests I could update. (And unfortunately I don't have time to add them.)
---------
In 0.4.5, after #195 was merged, a bug was introduced in an Altis client's application. If an application previously filtered `get_comments_number` (for example, to not count author replies when showing a comment count), that filtering would be undone by the filter in this module.
Example: if you had this code in an Altis application using Bylines,
```php
function get_author_reply_count( int $post_id ) : int {
$byline_users = Bylines\get_all_byline_authors( $post_id ); …
```
> Subtract workflow count from comment count instead of overwriting

- lib/destinations/email.php
#177 reported a bug that email subjects contained encoded characters which did not display correctly in some email clients. 
The suggested fix was to use [`wp_specialchars_decode`](https://developer.wordpress.org/reference/functions/wp_specialchars_decode/) and this was added in #178. 
However... one case specifically mentioned in the original bug was "em-dash". And this is not fixed!
Why is this and why is it important? Well `wptexturise` converts the `-` character to an em-dash encoded as `&#8211;`, and this does not get decoded by wp_specialchars_decode! (There is a comment on the developer docs flagging this). 
So what is the solution? Probably we can just use `html_entity_decode` instead.
> Use html_entity_decode not wp_specialchars_decode

- admin/src/WorkflowUI.js
- inc/class-rest-workflows-controller.php
To fix issue #161 
1. Add a new workflow.
2. Under "When should the workflow run?" dropdown, select any value.
3. Fill in any subject and message under "What message should be sent?"
4. Set "Specific users..." under "Who should be notified?"
5. In the user selection dropdown, choose a user.
6. Start typing to search for a user. If the dropdown list updates and does not include the previously selected user, that user will disappear from the field.
7. The user will reappear only if the dropdown list again contains the previously selected user.
For more details, watch this video: https://share.cleanshot.com/97dbyHry
---
1. **Backend (PHP):**
- The backend now checks if the recipient type is 'user'. If so, it loops through the selected values and returns an array of users with `id` and `name` …
> Fix #161 user select in workflows removed selected values
